version: '3'
services:
  app:
    container_name: docker_node_mongo
    restart: always
    build: .
    ports:
      - '5001:5001'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'